version: "3.8"

services:
  DailyhotApi:
    build:
      context: .
      target: runner
    image: dailyhot-api
    container_name: dailyhota_api
    ports:
      - "6688:6688"
    volumes:
      - "./logs:/app/logs"
    environment:
      - PORT=6688
    user: "114514"
    restart: always
